### PR TITLE
Generate error if IP list is empty

### PR DESCRIPTION
**Pull request by christarazi**
It would be a good idea to make sure the IP list is not empty before proceeding. This is a very basic fix for now, so it's probably best to generate a specific error for each particular condition. Let me know if you'd like me to change anything. 

**Context**:
I was running to problems when entering the `network` option. I was doing `set network 192.168.1.0` which the program accepted. Then after doing `run`, it would come up with a `TypeError` in `statusWidget()`. I realized that the `status` variable was not being initialized because the threads had no work to do because there wasn't any IP addresses to scan (the list was empty). 

Also, it would be a good idea to have some documentation or usage instructions. I assumed the program would be smart enough to realize the subnet without entering the `/24`.

### CODE REVIEW

**Comment by xdavidhu** [comment]
Hi, nice temporary fix, but could you please add it to all of the modules?

**Comment by christarazi** [comment]
@xdavidhu Amended my commit to include all the modules. Thanks for pointing that out.

**Comment by xdavidhu** [comment]
Thank you!

Unfortunately I still cant see the gameserver module in the commit, but I will merge it anyways and add  the the fix to the gameserver module as well.

Thank you for your contribution!

**Comment by christarazi** [comment]
Oops, I must have forgotten to `git add modules/gameserver.py`, sorry about that! I look forward to playing around with the project some more!

**Pull request merged**
